puts "there are #{100} cars available"
puts "there are only #{30} drivers available"
puts "there will be #{100 - 30} empty cars today"
puts " we can transport #{30 * 4.0}people today"
puts "we have #{90} to carpool today."
puts "we need to put about #{90 / 30}"
