puts "Mary had a little lamb."
puts "Its fleece was white as #{'snow'}."
puts "And everywhere that Mary went."
puts ".........."
#end1 = "C"
#end2 = "h"
#end3 = "e"
#end4 = "e"
#end5 = "s"
#end6 = "e"
#end7 = "B"
#end8 = "u"
#end9 = "r"
#end10 = "g"
#end11 = "e"
#end12 = "r"
print "cheese"
puts "Burger"
